USE [master]
GO
--drop database QLBVIEN1
go
/****** Object:  Database [QLBVIEN]    Script Date: 11/26/2024 8:50:36 AM ******/
CREATE DATABASE [QLBVIEN1]
 GO
USE [QLBVIEN1]
GO

select *
from [DICHVU]
go

SELECT *
FROM [CHINHANH]
GO

select *
from [DV_TTKHAM]
go
/****** Object:  Table [dbo].[CHINHANH]    Script Date: 11/26/2024 8:50:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHINHANH](
	[IDChiNhanh] [int] IDENTITY(1,1) NOT NULL,
	[MaChiNhanh] [varchar](10) NULL,
	[TenChiNhanh] [nvarchar](50) NULL,
	[DiaChi] [nvarchar](50) NULL,
	[IDQuanLy] [int] NULL,
	[IDNguon] [int] NULL,
	[NgayTao] [date] NULL,
	[NgayCapNhat] [date] NULL,
 CONSTRAINT [PK_CHINHANH] PRIMARY KEY CLUSTERED 
(
	[IDChiNhanh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DICHVU]    Script Date: 11/26/2024 8:50:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DICHVU](
	[IDDichVu] [int] IDENTITY(1,1) NOT NULL,
	[MaLoaiXetNghiem] [varchar](50) NULL,
	[TenLoaiXetNghiem] [nvarchar](50) NULL,
	[GiaXetNghiem] [money] NULL,
	[IDNguon] [int] NULL,
	[NgayTao] [date] NULL,
	[NgayCapNhat] [date] NULL,
 CONSTRAINT [PK_DICHVU] PRIMARY KEY CLUSTERED 
(
	[IDDichVu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DV_TTKHAM]    Script Date: 11/26/2024 8:50:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DV_TTKHAM](
	[IDKham] [int]  NOT NULL,
	[IDDichVu] [int] NOT NULL,
	[IDNhanVien] [int] NULL,
	[IDVaiTro] [int] NULL,
 CONSTRAINT [PK_DV_TTKHAM] PRIMARY KEY CLUSTERED 
(
	[IDKham] ASC,
	[IDDichVu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NGUON]    Script Date: 11/26/2024 8:50:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NGUON](
	[IDNguon] [int] IDENTITY(1,1) NOT NULL,
	[TenNguon] [varchar](50) NULL,
 CONSTRAINT [PK_NGUON] PRIMARY KEY CLUSTERED 
(
	[IDNguon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

insert into [dbo].[NGUON](TenNguon)
values('MSSQL_TpHCM'),
('XLXS_HaNoi');
GO


/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 11/26/2024 8:50:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[IDNhanVien] [int] IDENTITY(1,1) NOT NULL,
	[MaNV] [varchar](10) NULL,
	[HoTen] [nvarchar](50) NULL,
	[SoDienThoai] [varchar](50) NULL,
	[DiaChi] [nvarchar](50) NULL,
	[Luong] [money] NULL,
	[MaChiNhanh] [int] NULL,
	[IDNguon] [int] NULL,
	[NgayTao] [date] NULL,
	[NgayCapNhat] [date] NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[IDNhanVien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NV_VT]    Script Date: 11/26/2024 8:50:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NV_VT](
	[IDVaiTro] [int] NOT NULL,
	[IDNhanVien] [int] NOT NULL,
 CONSTRAINT [PK_NV_VT] PRIMARY KEY CLUSTERED 
(
	[IDVaiTro] ASC,
	[IDNhanVien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[VAITRO]    Script Date: 11/26/2024 8:50:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VAITRO](
	[IDVaiTro] [int] IDENTITY(1,1) NOT NULL,
	[MaVaiTro] [varchar](10) NULL,
	[TenVaiTro] [nvarchar](50) NULL,
	[HeSo] [decimal](3, 2) NOT NULL,
	[IDNguon] [int] NULL,
	[NgayTao] [date] NULL,
	[NgayCapNhat] [date] NULL,
 CONSTRAINT [PK_VAITRO] PRIMARY KEY CLUSTERED 
(
	[IDVaiTro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

Select IDChiNhanh, IDNguon
From CHINHANH ch, NGUON n
Where n.TenNguon = ch.SourceName

GO
ALTER TABLE [dbo].[CHINHANH]  WITH CHECK ADD  CONSTRAINT [FK_CHINHANH_NGUON] FOREIGN KEY([IDNguon])
REFERENCES [dbo].[NGUON] ([IDNguon])
GO
ALTER TABLE [dbo].[CHINHANH] CHECK CONSTRAINT [FK_CHINHANH_NGUON]
GO
ALTER TABLE [dbo].[CHINHANH]  WITH CHECK ADD  CONSTRAINT [FK_CHINHANH_NHANVIEN] FOREIGN KEY([IDQuanLy])
REFERENCES [dbo].[NHANVIEN] ([IDNhanVien])
GO
ALTER TABLE [dbo].[CHINHANH] CHECK CONSTRAINT [FK_CHINHANH_NHANVIEN]
GO
ALTER TABLE [dbo].[DICHVU]  WITH CHECK ADD  CONSTRAINT [FK_DICHVU_NGUON] FOREIGN KEY([IDNguon])
REFERENCES [dbo].[NGUON] ([IDNguon])
GO
ALTER TABLE [dbo].[DICHVU] CHECK CONSTRAINT [FK_DICHVU_NGUON]
GO
ALTER TABLE [dbo].[DV_TTKHAM]  WITH CHECK ADD  CONSTRAINT [FK_DV_TTKHAM_DICHVU] FOREIGN KEY([IDDichVu])
REFERENCES [dbo].[DICHVU] ([IDDichVu])
GO
ALTER TABLE [dbo].[DV_TTKHAM] CHECK CONSTRAINT [FK_DV_TTKHAM_DICHVU]
GO
ALTER TABLE [dbo].[DV_TTKHAM]  WITH CHECK ADD  CONSTRAINT [FK_DV_TTKHAM_NV_VT] FOREIGN KEY([IDNhanVien], [IDVaiTro])
REFERENCES [dbo].[NV_VT] ([IDVaiTro], [IDNhanVien])
GO
ALTER TABLE [dbo].[DV_TTKHAM] CHECK CONSTRAINT [FK_DV_TTKHAM_NV_VT]
GO
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_NHANVIEN_CHINHANH] FOREIGN KEY([MaChiNhanh])
REFERENCES [dbo].[CHINHANH] ([IDChiNhanh])
GO
ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [FK_NHANVIEN_CHINHANH]
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [FK_NHANVIEN_NGUON] FOREIGN KEY([IDNguon])
REFERENCES [dbo].[NGUON] ([IDNguon])
GO
ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [FK_NHANVIEN_NGUON]
GO
ALTER TABLE [dbo].[NV_VT]  WITH CHECK ADD  CONSTRAINT [FK_NV_VT_NHANVIEN] FOREIGN KEY([IDNhanVien])
REFERENCES [dbo].[NHANVIEN] ([IDNhanVien])
GO
ALTER TABLE [dbo].[NV_VT] CHECK CONSTRAINT [FK_NV_VT_NHANVIEN]
GO
ALTER TABLE [dbo].[NV_VT]  WITH CHECK ADD  CONSTRAINT [FK_NV_VT_VAITRO] FOREIGN KEY([IDVaiTro])
REFERENCES [dbo].[VAITRO] ([IDVaiTro])
GO
ALTER TABLE [dbo].[NV_VT] CHECK CONSTRAINT [FK_NV_VT_VAITRO]
go
ALTER TABLE [dbo].[VAITRO]  WITH CHECK ADD  CONSTRAINT [FK_VAITRO_NGUON] FOREIGN KEY([IDNguon])
REFERENCES [dbo].[NGUON] ([IDNguon])
GO
ALTER TABLE [dbo].[VAITRO] CHECK CONSTRAINT [FK_VAITRO_NGUON]
GO
USE [master]
GO
ALTER DATABASE [QLBVIEN] SET  READ_WRITE 
GO
